### ISSUE TITLE
Examples Don't Work: `could not find 'Cargo.toml' in '/app' or any parent directory` 

### ISSUE THREAD

**Issue by XAMPPRocky** [LukeMathWalker/cargo-chef#147]
Copying this example `Dockerfile` into my project doesn't work. It shouldn't matter, but I'm on ARM macOS 12.3.1.

### Steps

1. Clone [`quilkin`](https://github.com/googleforgames/quilkin)
2. Paste the `Dockerfile` below into the root of the project.
3. Run `docker build .`

### Dockerfile

```docker
FROM lukemathwalker/cargo-chef:latest-rust-1.56.0 AS chef
WORKDIR app

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder 
COPY --from=planner /app/recipe.json recipe.json
# Build dependencies - this is the caching Docker layer!
RUN cargo chef cook --release --recipe-path recipe.json
# Build application
COPY . .
RUN cargo build --release --bin app

# We do not need the Rust toolchain to run the binary!
FROM debian:buster-slim AS runtime
WORKDIR app
COPY --from=builder /app/target/release/app /usr/local/bin
ENTRYPOINT ["/usr/local/bin/app"]
```

### Error

```
 > [builder 2/4] RUN RUST_BACKTRACE=1 cargo chef cook --workspace --release --recipe-path recipe.json:
#13 0.211 error: could not find `Cargo.toml` in `/app` or any parent directory
#13 0.211 thread 'main' panicked at 'Exited with status code: 101', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/cargo-chef-0.1.38/src/recipe.rs:1
56:27
#13 0.211 stack backtrace:
#13 0.215    0: rust_begin_unwind
#13 0.215              at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
#13 0.215    1: core::panicking::panic_fmt
#13 0.215              at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
#13 0.215    2: chef::recipe::Recipe::cook
#13 0.215    3: cargo_chef::main
#13 0.215 note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by LukeMathWalker** [comment]
Your .dockerignore file is pretty much removing all files from the build context - you can see it by adding a `RUN find -maxdepth 2 -type d -ls` after the `COPY . .`:
```
Step 5/15 : RUN find -maxdepth 2 -type d -ls
  2370706      4 drwxr-xr-x   1 root     root         4096 Aug  8 09:00 .
  2370711      4 drwxr-xr-x   2 root     root         4096 Aug  8 08:53 ./image
```
`cargo-chef` cannot find any `Cargo.toml` file because there is none 😅

**Comment by XAMPPRocky** [comment]
Ah thanks for that! 😄 I didn't write that file so I forgot to even check for it.
