### ISSUE TITLE
Can't find some path

### ISSUE THREAD

**Issue by TriplEight** [LukeMathWalker/cargo-chef#16]
Hello,
I'm experimenting further after #11 and faced something new. 
When in the virtual workspace, and need to build something specific:

<details>
<summary>Error:</summary>

```
root@ced6a778bc7f:/builds/bin/utils/subkey# cargo chef cook --release --recipe-path recipe.json
error: failed to parse manifest at `/builds/bin/utils/subkey/primitives/core/Cargo.toml`

Caused by:
  can't find `bench` bench, specify bench.path
thread 'main' panicked at 'Exited with status code: 101', src/recipe.rs:82:27
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: std::panicking::begin_panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:429
   2: chef::recipe::Recipe::cook
   3: cargo_chef::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

<details>
<summary>Repro:</summary>

run an image

```
docker run -it paritytech/ci-linux:3ec7097e-20201113
```

and there

```
cargo install --git https://github.com/NathanHowell/cargo-chef --branch with-manifest-fixes

git clone https://github.com/paritytech/substrate .
# variant 1
cd ./bin/utils/subkey
cargo chef prepare  --recipe-path recipe.json
cargo chef cook --release --recipe-path recipe.json

# variant 2
cargo chef prepare  --recipe-path recipe.json
cd ./bin/utils/subkey
cargo chef cook --release --recipe-path ../../../recipe.json

```

</details>

**Comment by NathanHowell** [comment]
@TriplEight if you want to kick the tires on https://github.com/NathanHowell/cargo-plan this seems to work for me:
```sh
cargo plan create
mkdir x
pushd x
cargo plan build -f ../cargo-plan.tar -- --package subkey
```

**Comment by LukeMathWalker** [comment]
I successfully managed to run the second variant with `cargo-chef:0.1.7`.

**Comment by TriplEight** [comment]
Yup, it works now, thanks!
