### ISSUE TITLE
'Exited with status code: 101', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/cargo-chef-0.1.51/src/recipe.rs:176:27

### ISSUE THREAD

**Issue by lcmgh** [LukeMathWalker/cargo-chef#189]
```bash
#18 [builder  8/14] RUN cargo chef cook --release --all-targets --recipe-path recipe.json
#18 0.646 error: output of --print=file-names has changed in the compiler, cannot parse
#18 0.646 command was: `/usr/local/cargo/bin/cachepot rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg`
#18 0.646 
#18 0.646 --- stdout
#18 0.646 Soon to be the better sccache
#18 0.646 
#18 0.648 thread 'main' panicked at 'Exited with status code: 101', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/cargo-chef-0.1.51/src/recipe.rs:176:27
#18 0.648 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
#18 ERROR: process "/bin/sh -c cargo chef cook --release --all-targets --recipe-path recipe.json" did not complete successfully: exit code: 101
------
 > [builder  8/14] RUN cargo chef cook --release --all-targets --recipe-path recipe.json:
#18 0.646 error: output of --print=file-names has changed in the compiler, cannot parse
#18 0.646 command was: `/usr/local/cargo/bin/cachepot rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg`
#18 0.646 
#18 0.646 --- stdout
#18 0.646 Soon to be the better sccache
#18 0.646 
#18 0.648 thread 'main' panicked at 'Exited with status code: 101', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/cargo-chef-0.1.51/src/recipe.rs:176:27
#18 0.648 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------
Dockerfile:33
--------------------
  31 |     COPY --from=planner /app/recipe.json recipe.json
  32 |     # Build dependencies - this is the caching Docker layer!
  33 | >>> RUN cargo chef cook --release --all-targets --recipe-path recipe.json
  34 |     
  35 |     COPY . /build
--------------------
ERROR: failed to solve: process "/bin/sh -c cargo chef cook --release --all-targets --recipe-path recipe.json" did not complete successfully: exit code: 101
Error: Process completed with exit code 1.
```

**Comment by LukeMathWalker** [comment]
This looks a cachepot error, not a cargo-chef one.

**Comment by lcmgh** [comment]
I will play around a bit and report back with more details. Thanks for the first hint.
