### ISSUE TITLE
losts version during prepare and cannot find proper version during cooking

### ISSUE THREAD

**Issue by dzmitry-lahoda** [LukeMathWalker/cargo-chef#99]
```shell
INFO[1781] Running: [/bin/sh -c cargo chef cook --check --tests --all-targets --package service-contracts --recipe-path recipe.json] 
    Updating crates.io index
error: failed to select a version for the requirement `marine-rs-sdk = "^0.0.1"`
candidate versions found which didn't match: 0.6.14, 0.6.13, 0.6.12, ...
location searched: crates.io index
required by package `service-contracts v0.0.1 (/service-contracts)`
thread 'main' panicked at 'Exited with status code: 101', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-chef-0.1.31/src/recipe.rs:145:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 101
```

really, all is defined well here:

```toml
[package]
name = "service-contracts"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "service-contracts"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.31"
base64 = "0.13.0"
boolinator = "2.4.0"
chrono = "0.4"
marine-rs-sdk = {version = "0.6.14"}
log = "0.4.8"
num-derive = "0.3.3"
num-traits = "0.2"
once_cell = "1.4.1"
rusty_ulid = "0.11.0"
serde = { version="1", features=["derive"] }
serde_json = "1"
thiserror = "1"
uuid = { version="0.8.1", features=["v4"] }
paste = "*"
```
version
```
$ cargo chef --version
info: syncing channel updates for 'nightly-2021-09-01-x86_64-unknown-linux-gnu'
info: latest update on 2021-09-01, rust version 1.56.0-nightly (29ef6cf16 2021-08-31)
info: component 'rust-std' for target 'x86_64-unknown-linux-gnu' is up to date
info: downloading component 'rust-std' for 'x86_64-apple-darwin'
info: installing component 'rust-std' for 'x86_64-apple-darwin'
cargo-chef 0.1.31
$ cargo --version
cargo 1.56.0-nightly (f559c109c 2021-08-26)
````

I retained only one project and manually checked the there is one and only one version of all crates in locally running chef. On WS2 it seems work locally, but on GitLab docker it does not work well. On GitLab, before clean up I got https://github.com/LukeMathWalker/cargo-chef/issues/43#issuecomment-942606222  (even with bad version it works locally, but after retaining one and only one project something else happening).

**Comment by jinq0123** [comment]
[ctrlc.zip](https://github.com/LukeMathWalker/cargo-chef/files/7593046/ctrlc.zip)

This is a simple test.
`ctrlc = "3.2.1"` will be OK, but `ctrlc = { version = "3.2.1" }` failed.

```
>docker build . --tag ctrlc:0.3
...
 => CACHED [builder 1/4] COPY --from=planner /test/recipe.json recipe.json                                         0.0s
 => ERROR [builder 2/4] RUN cargo chef cook --release --recipe-path recipe.json                                   28.7s
------
 > [builder 2/4] RUN cargo chef cook --release --recipe-path recipe.json:
#14 0.797     Updating crates.io index
#14 28.68 error: failed to select a version for the requirement `ctrlc = "=0.0.1"`
#14 28.68 candidate versions found which didn't match: 3.2.1, 3.2.0, 3.1.10, ...
#14 28.68 location searched: crates.io index
#14 28.68 required by package `ctrlc v0.0.1 (/test)`
#14 28.68 thread 'main' panicked at 'Exited with status code: 101', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/cargo-chef-0.1.31/src/recipe.rs:145:27
#14 28.68 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------
executor failed running [/bin/sh -c cargo chef cook --release --recipe-path recipe.json]: exit code: 101
```

**Comment by jinq0123** [comment]
I solved the problem by renaming my package name, which conflicts with dependency crate 'ctrlc'.

**Comment by LukeMathWalker** [comment]
I'll close then!

**Comment by jinq0123** [comment]
`cargo chef cook` should succeed as `cargo build` do.

**Comment by dzmitry-lahoda** [comment]
repo i worked on used gitlab cache instead of cargo chef based docker cache which is vendor locking, soon it will be oss, but it will not have chef used
